Update CountrySelect to be one file, add tests
bcgov/common-lib-vue pull request #154
Opened 2022-05-04 21:46 UTC by bryce-mcmath

### Please check if the PR fulfills these requirements:

- [ ] After these changes, the app was run and still works as expected
- [x] Tests for these changes were added (if applicable)
- [ ] All existing unit tests were run and still pass

### Please specify the type of change this PR introduces (Bug fix, feature addition, content update, chore, etc.):
Chore (vue3 upgrade)

### Additional Notes:

2022-05-04 21:54 UTC, harrymaynard-maximus requested changes

2022-05-04 21:54 UTC, harrymaynard-maximus commented on src/components/CountrySelect.vue
> +      <option v-if="topCountry" :value="firstCountry"
Missing a line break here (`:value="..."`).

2022-05-04 21:58 UTC, bryce-mcmath commented on src/components/CountrySelect.vue
> +      <option v-if="topCountry" :value="firstCountry"
Added

2022-05-04 21:59 UTC, harrymaynard-maximus approved these changes
Looks good. Nice job!

2022-05-05 17:42 UTC, jlangy approved these changes

2022-05-05 18:36 UTC, merged