Number select
bcgov/common-lib-vue pull request #170
Opened 2022-05-10 23:10 UTC by jlangy

### Please check if the PR fulfills these requirements:

- [ ] After these changes, the app was run and still works as expected
- [x] Tests for these changes were added (if applicable)
- [ ] All existing unit tests were run and still pass

### Please specify the type of change this PR introduces (Bug fix, feature addition, content update, chore, etc.):
chore
### Additional Notes:

2022-05-10 23:44 UTC, bryce-mcmath approved these changes

2022-05-11 16:19 UTC, harrymaynard-maximus requested changes

2022-05-11 17:01 UTC, jlangy commented on src/components/NumberSelect.vue
> +      this.$emit('update:modelValue', event?.target?.value);
Sure, do you think we should get rid of them? I have a bit of a habit of adding them when not using typescript, but you're right it shouldn't ever be needed, `event` and `event.target` should always be defined

2022-05-11 17:29 UTC, harrymaynard-maximus approved these changes
Looks good.

2022-05-11 17:30 UTC, merged